Repository sonatype-nexus-community/sonatype-platform-reference, pull requests merged in 2024-10, with the labels that each got.

#12 apply Sonatype rebranding
  .env-example
  README.md
  config/nexus-iq-config.yaml
  config/nginx-cicd-teamcity.conf
  config/nginx-cicd.conf
  config/nginx-www-template/index.html.template
  config/nginx-www/index.html
  config/nginx.conf
Labels: :anguished: commits missing verification, :heart_eyes: cla signed

#18 doc: complete first use instructions
  README.md
Labels: documentation

#17 fix: IQ connection to PostgreSQL added in 8e50c5a
  .env-example
  docker-compose.yml
Labels: bug, :heart_eyes: cla signed

#20 drop Fortify SSC setup
  .env-example
  README.md
  docker-compose.yml
Labels: :heart_eyes: cla signed

#23 automate .env for arm from .env-example
  README.md
Labels: enhancement, :heart_eyes: cla signed

#22 doc: corrected branding and included Sonatype SBOM Manager
  README.md
Labels: documentation, :heart_eyes: cla signed

#24 drop Fortify license requirement #20
  docker-compose.yml
Labels: bug, :heart_eyes: cla signed

#29 fix: set UID/GID for PostgreSQL data volume
  .env-example
  README.md
  docker-compose.yml
Labels: bug, :heart_eyes: cla signed

#30 fix: ensure PostgreSQL is accessible by proxied and direct IQ instances
  docker-compose.yml
Labels: bug, :heart_eyes: cla signed

#25 upgrade Sonatype platform to current releases by default
  .env-example
Labels: enhancement, :heart_eyes: cla signed

#31 fix: missing -e in sed command
  README.md
Labels: :heart_eyes: cla signed

#19 move Dockerfiles to images/
  docker-compose.yml
  examples/docker-compose-nxrm-only/docker-compose.yml
  images/jenkins/Dockerfile
  images/jenkins/plugins.txt
  images/nginx/Dockerfile
  images/nginx/nginx.conf
  images/nginx/proxy_params
  images/nxrm3/Dockerfile
  images/teamcity-agent-windows/Dockerfile
  images/teamcity-agent/Dockerfile
  images/teamcity-server/Dockerfile
Labels: enhancement

#39 fix remaining Nexus -> Sonatype branding
  config/nginx-www-template/index.html.template
Labels: :heart_eyes: cla signed

#38 feat: use docker volumes & nxrm pro to use PostgreSQL
  config/nexus-iq-config.yaml
  docker-compose.yml
Labels: enhancement, :heart_eyes: cla signed

#40 feat: remove Team City related configuration and profile
  README.md
  config/nginx-cicd-teamcity.conf
  docker-compose.yml
  images/teamcity-agent-windows/Dockerfile
  images/teamcity-agent/Dockerfile
  images/teamcity-server/Dockerfile
Labels: enhancement, :heart_eyes: cla signed

#42 fix: avoid postgres-nxrm-1 FATAL: sorry, too many clients already
  docker-compose.yml
Labels: bug, :heart_eyes: cla signed

#41 feat: Remove CASC Plugin and associated configuration as unused
  .env-example
  README.md
  config/admin_password
  config/nexus-repo-casc-oss.yaml
  config/nexus-repo-casc.yaml
  config/nexus-repo.properties
  config/nginx-www-template/index.html.template
  docker-compose.yml
  examples/docker-compose-nxiq-only/docker-compose.yml
  examples/docker-compose-nxrm-only/docker-compose.yml
  images/nxrm3/Dockerfile
Labels: enhancement, :heart_eyes: cla signed
